---
version: "2.0"
services:
  service-rpow:
    image: toanbk/rpow2:v3
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - GROUP_NAME=__PLACEHOLDER__
profiles:
  compute:
    service-rpow:
      resources:
        cpu:
          units: 2
        memory:
          size: 4gb
        storage:
          - size: 30gb
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        service-rpow:
          denom: uact
          amount: 100000
deployment:
  service-rpow:
    dcloud:
      profile: service-rpow
      count: 1
